### ISSUE TITLE
issue in latest RR rom on SM-N900

### ISSUE THREAD

**Issue by FXlife** [ResurrectionRemix-OTA-Server/resurrectionremix-ota-server.github.io#7]
After installation, speaker play music low......like speaker is broken....even though is the latest version.
I see that other phones received updates but for Note 3 n900 it's still Nov 21th.....

Please I search every where and the only way I found to contact your team is by this.

**Comment by TheComputerGuy96** [comment]
Could you better ask on Google+?:
https://plus.google.com/communities/109352646351468373340
